### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by bzhar93** [kaisbe/cybrary-dl#1]
it won't connect to cybrary when i type the correct username and password it will show Authentication failure

**Comment by krisk1712** [comment]
i have the same problem too. Please do help out this issue

**Comment by kaisbe** [comment]
Thanks for reporting this, but the root cause of this problem is the HTTP 502 error code caused by the server. I have tried to update the headers, but it didn't solve the problem either. This issue requires a certain effort and I'm not going to work on it right now - someone else can help with this, and PRs are welcome.
